ORGANIZATION_TO_URL = {
    'actifio': 'https://www.owler.com/iaApp/123706/actifio-news',
    'adaptive-biotechnologies': 'https://www.owler.com/iaApp/383771/adaptive-biotechnologies-news',
    'affirm': 'https://www.owler.com/iaApp/1195149/affirm-news',
    'airbnb': 'https://www.owler.com/iaApp/116231/airbnb-news',
    'angellist': 'https://www.owler.com/iaApp/116312/angellist-news',
    'appnexus': 'https://www.owler.com/iaApp/104201/appnexus-news',
    'automattic': 'https://www.owler.com/iaApp/102038/automattic-news',
    'beepi': 'https://www.owler.com/iaApp/1395944/beepi-news',
    'big-health': 'https://www.owler.com/iaApp/1410777/big-health-news',
    'birchbox':'https://www.owler.com/iaApp/100239/birchbox-news',
    'bitgo': 'https://www.owler.com/iaApp/1392180/bitgo-news',
    'bitpay': 'https://www.owler.com/iaApp/143463/bitpay-news',
    'blue-apron': 'https://www.owler.com/iaApp/209992/blue-apron-news',
    'bonobos': 'https://www.owler.com/iaApp/100338/bonobos-news',
    'box': 'https://www.owler.com/iaApp/102324/box-news',
    'carmenta-bioscience': 'https://www.owler.com/iaApp/219912/carmenta-bioscience-news',
    'chain-2': 'https://www.owler.com/iaApp/1624975/chain-news',
    'nfc-direct': 'https://www.owler.com/iaApp/707356/circle-news',
    'cloudera': 'https://www.owler.com/iaApp/100508/cloudera-news',
    'coinbase': 'https://www.owler.com/iaApp/137494/coinbase-news',
    'coursera': 'https://www.owler.com/iaApp/123087/coursera-news',
    'datafox': 'https://www.owler.com/iaApp/1185370/datafox-news',
    'docusign': 'https://www.owler.com/iaApp/120886/docusign-news',
    'dollar-shave-club': 'https://www.owler.com/iaApp/134638/dollar-shave-club-news',
    'domo': 'https://www.owler.com/iaApp/108757/domo-news',
    'doordash': 'https://www.owler.com/iaApp/217990/doordash-news',
    'dropbox': 'https://www.owler.com/iaApp/101638/dropbox-news',
    'duck-duck-go':'https://www.owler.com/iaApp/113057/duckduckgo-news',
    'ecovent':'https://www.owler.com/iaApp/1408573/ecovent-systems-news',
    'etsy': 'https://www.owler.com/iaApp/121413/etsy-news',
    'eventbrite': 'https://www.owler.com/iaApp/100125/eventbrite-news',
    'fab-com': 'https://www.owler.com/iaApp/101152/fab-news',
    'fastly': 'https://www.owler.com/iaApp/172675/fastly-news',
    'flipkart': 'https://www.owler.com/iaApp/139206/flipkart-news',
    'github': 'https://www.owler.com/iaApp/128666/github-news',
    'good-eggs': 'https://www.owler.com/iaApp/365160/good-eggs-news',
    'homejoy': 'https://www.owler.com/iaApp/183855/homejoy-news',
    'houzz': 'https://www.owler.com/iaApp/135032/houzz-news',
    'hubspot':'https://www.owler.com/iaApp/100163/hubspot-news',
    'ifttt': 'https://www.owler.com/iaApp/125005/ifttt-news',
    'imgur': 'https://www.owler.com/iaApp/122272/imgur-news',
    'jawbone': 'https://www.owler.com/iaApp/125318/jawbone-news',
    'julep': 'https://www.owler.com/iaApp/141657/julep-news',
    'knewton': 'https://www.owler.com/iaApp/100158/knewton-news',
    'leap-motion': 'https://www.owler.com/iaApp/139746/leap-motion-news',
    'livingsocial': 'https://www.owler.com/iaApp/104280/livingsocial-news',
    'lookout': 'https://www.owler.com/iaApp/123609/lookout-news',
    'ltg-exam-prep-platform':'https://www.owler.com/iaApp/490087/ltg-news',
    'lyft':'https://www.owler.com/iaApp/123687/lyft-news',
    'mapr-technologies': 'https://www.owler.com/iaApp/100509/mapr-news',
    'mattermark': 'https://www.owler.com/iaApp/172098/mattermark-news',
    'medium': 'https://www.owler.com/iaApp/229499/medium-news',
    'mightytext': 'https://www.owler.com/iaApp/144329/mightytext-news',
    'mongodb-inc': 'https://www.owler.com/iaApp/125134/mongodb-news',
    'nextdoor': 'https://www.owler.com/iaApp/139804/nextdoor-news',
    'okta':'https://www.owler.com/iaApp/124415/okta-news',
    'optimizely': 'https://www.owler.com/iaApp/105382/optimizely-news',
    'palantir-technologies': 'https://www.owler.com/iaApp/133110/palantir-news',
    'path': 'https://www.owler.com/iaApp/121985/path-news',
    'pinterest': 'https://www.owler.com/iaApp/111996/pinterest-news',
    'platfora': 'https://www.owler.com/iaApp/106567/platfora-news',
    'practice-fusion': 'https://www.owler.com/iaApp/122374/practice-fusion-news',
    'product-hunt': 'https://www.owler.com/iaApp/1484621/product-hunt-news',
    'pure-storage': 'https://www.owler.com/iaApp/122756/pure-storage-news',
    'reddit':'https://www.owler.com/iaApp/104254/reddit-news',
    'ripple-labs': 'https://www.owler.com/iaApp/147208/ripple-labs-news',
    #'sand-hill-exchange-2'
    'secondmarket': 'https://www.owler.com/iaApp/123317/secondmarket-news',
    'secret': 'https://www.owler.com/iaApp/1183296/secret-news',
    'sendgrid': 'https://www.owler.com/iaApp/124152/sendgrid-news',
    'shyp': 'https://www.owler.com/iaApp/490204/shyp-news',
    'tiny-speck': 'https://www.owler.com/iaApp/359234/slack-news',
    'snapchat': 'https://www.owler.com/iaApp/141188/snapchat-news',
    'social-finance': 'https://www.owler.com/iaApp/139446/sofi-news',
    'sosh': 'https://www.owler.com/iaApp/358911/sosh-news',
    'square': 'https://www.owler.com/iaApp/102407/square-news',
    'stripe':'https://www.owler.com/iaApp/100441/stripe-news',
    'theranos': 'https://www.owler.com/iaApp/139733/theranos-news',
    'thrillist-com': 'https://www.owler.com/iaApp/100198/thrillist-news',
    'tinder': 'https://www.owler.com/iaApp/180478/tinder-news',
    'twilio': 'https://www.owler.com/iaApp/124188/twilio-news',
    'uber': 'https://www.owler.com/iaApp/100242/uber-news',
    #'vurb'
    'warby-parker': 'https://www.owler.com/iaApp/100305/warby-parker-news',
    'washio': 'https://www.owler.com/iaApp/1147581/washio-news',
    'wealthfront': 'https://www.owler.com/iaApp/122326/wealthfront-news',
    'wefunder': 'https://www.owler.com/iaApp/110408/wefunder-news',
    'yo': 'https://www.owler.com/iaApp/1530962/yo--news',
    'zenefits': 'https://www.owler.com/iaApp/217994/zenefits-news',
    'zocdoc': 'https://www.owler.com/iaApp/125194/zocdoc-news'
    }
