STANDARD_FEEDS = {
    'techcrunch': 'http://techcrunch.com/feed/',
    'venturebeat': 'http://venturebeat.com/feed/',
    'xconomy': 'http://www.xconomy.com/feed/',
    'mashable': 'http://mashable.com/category/startups/rss/',
    'foxbusiness': 'http://smallbusiness.foxbusiness.com/home/feed/rss/',
    'wired': 'http://feeds.wired.com/wired/index',
    'nytimes': 'http://bits.blogs.nytimes.com/feed/',
    'businessinsider': 'http://www.businessinsider.com/rss',
    'springwise': 'http://www.springwise.com/feed/',
    'mercurynews': 'http://feeds.mercurynews.com/mngi/rss/CustomRssServlet/568/200774.xml',
    'bloombergview': 'http://www.bloombergview.com/rss',
    'forbes': 'http://www.forbes.com/technology/index.xml',
    'timesofindia': 'http://timesofindia.feedsportal.com/c/33039/f/533923/index.rss',
    'coindesk': 'http://www.coindesk.com/feed/',
    'theatlantic': 'http://feeds.feedburner.com/AtlanticScienceAndTechnology?format=xml',
    'beatbeat': 'http://betabeat.com/feed/',
    'fortune': 'http://fortune.com/feed/',
    'recode': 'http://recode.net/feed/',
    'newyorker': 'http://www.newyorker.com/rss',
    'gizmodo': 'http://gizmodo.com/rss',
    'cnet': 'http://www.cnet.com/rss/news/',
    'bgr': 'http://feeds.feedburner.com/TheBoyGeniusReport',
    'wefunder': 'https://wefunder.com/blog/feed.rss',
    'reuters_tech': 'http://feeds.reuters.com/reuters/technologyNews',
    'reuters_merger': 'http://feeds.reuters.com/reuters/mergersNews',
    'reuters_deals': 'http://feeds.reuters.com/news/deals',
    'reuters_ipo': 'http://www.reuters.com/rssFeed/newIssuesNews',
    'bizjournals': 'http://feeds.bizjournals.com/industry_7',
    'businessweek': 'http://www.businessweek.com/feeds/most-popular.rss',
    'time': 'http://time.com/tech/feed/',
    'itworld': 'http://www.itworld.com/taxonomy/term/43/all/feed?source=rss_mobile',
    'pcworld': 'http://www.pcworld.com/category/business/index.rss',
    'valleywag': 'http://valleywag.gawker.com/rss',
    # 'gigaom': 'https://gigaom.com/feed/', invalid SSL
    'wsj': 'http://online.wsj.com/xml/rss/3_7455.xml'}

# http://www.theverge.com/rss/frontpage, different do later
